version: "3.4"

services:
  synapse:
    container_name: "synapse"
    image: "matrixdotorg/synapse:latest"
    restart: "unless-stopped"
    ports:
      - "127.0.0.1:18008:8008"
      - "127.0.0.1:18448:8448"
    volumes:
      - "./data/:/data/"
